config/routes.rb
Rails.application.routes.draw do

root :to => 'users#index'

resources :users do
  resources :questions
end

resources :answers
end

app/models/answer.rb
class Answer < ActiveRecord::Base

  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base

  has_many :answers
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  validates :name, :presence => true
  validates_confirmation_of :password
  validates :email, :presence => true
  validates :email, uniqueness: true
  validates :password, length: { in: 6..20 }
  before_save :encrypt_password

  has_many :questions
  has_many :answers

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionController < ApplicationController

  def index
    @questions = User.all
  end

  def new
    @user = User.find(params[:user_id])
    @question = @user.questions.new
  end

  def create
    @user = User.find(params[:user_id])
    @question = @user.questions.new(question_params)
    if @question.save
      flash[:notice] = "Question has been added!"
      redirect_to user_index
    else
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
    @user = User.find(params[:user_id])
  end

  private
    def question_params
      params.require(:question).permit(:body)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @questions = Question.all
    @answers = Answer.all
  end

  def new
   @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User has been added!"
      redirect_to "/"
    else
      flash[:alert] = "There was a problem, yo."
      redirect_to :back
    end
  end

  def show
  end

  def update
  end



  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<span class="success"><%= flash[:notice] %></span>
<span class="fail"><%= flash[:alert] %></span>

<h1>Welcome to my Website</h1>
  <% if current_user %>
    <h3>You are logged in as: <span class="user"><%= current_user.email %></span></h3>
  <% end %>

  <% if @users.any? %>
    <% @users.each do |user| %>
    <ul>
      <li><%= user.email %></li>
    </ul>
    <% end %>
    <% end %>

<%= link_to "Add New User", new_user_path, :class => "btn btn-success" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StackOverflow</title>
  <link rel="stylesheet" href="app/assets/stylesheets/bootstrap_paper.css" media="screen" title="no title" charset="utf-8">
  <link rel="stylesheet" href="app/assets/stylesheets/styles.css" media="screen" title="no title" charset="utf-8">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= flash[:notice] %>
    <%= yield %>
  </div>
</body>
</html>

app/views/questions/new.html.erb
<% bootstrap_form_for [@user, @question] do |f| %>
<%= f.text_area :body, rows: 15 %>

<%= f.submit "Submit", class: 'btn-btn-info' %>
<% end %>

app/views/users/index.html.erb
<h1> Stack Overflow</h1>

<%= link_to "Add new user", new_user_path %>


<% if @users.any? %>
    <% @users.each  do |user| %>
    <ul>
     <li><%= link_to user.name, user_path(user) %></li>
    </ul>
    <% end %>
  <% end %>

app/views/users/new.html.erb
<h2>Please create a new user</h2>

<%= form_for @user do |f| %>
  <%=f.label :email %>
  <%=f.text_field :email %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%=f.label :password %>
  <%=f.password_field :password %>
  <%=f.label :password_confirmation %>
  <%=f.password_field :password_confirmation %>
  <%= f.submit "Sign up", class: 'btn-btn-primary' %>
<% end %>

app/views/users/show.html.erb
<h4>Welcome <%= @user.name %></h4>

<%= link_to "New Question", new_user_question_path(@user) %>

<% if @user.questions.any? %>
  <% @user.questions.each do |question| %>
  <ul>
    <li><%= link_to question.body, user_question_path(question) %></li>
  </ul>
  <% end %>
<% end %>